[2024-02-15T13:04:39.636+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:04:37.376118+00:00 [queued]>
[2024-02-15T13:04:39.641+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:04:37.376118+00:00 [queued]>
[2024-02-15T13:04:39.642+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-15T13:04:39.648+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_bigc_and_makro> on 2024-02-15 13:04:37.376118+00:00
[2024-02-15T13:04:39.654+0000] {standard_task_runner.py:57} INFO - Started process 1352 to run task
[2024-02-15T13:04:39.658+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_pipeline', 'get_data_from_bigc_and_makro', 'manual__2024-02-15T13:04:37.376118+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmp42r24w1j']
[2024-02-15T13:04:39.660+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask get_data_from_bigc_and_makro
[2024-02-15T13:04:39.698+0000] {task_command.py:415} INFO - Running <TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:04:37.376118+00:00 [running]> on host c0165191c622
[2024-02-15T13:04:40.022+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='my_pipeline' AIRFLOW_CTX_TASK_ID='get_data_from_bigc_and_makro' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T13:04:37.376118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-15T13:04:37.376118+00:00'
[2024-02-15T13:04:40.833+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_pipeline.py", line 128, in get_data_from_bigc_and_makro
    bigc_df = get_data_bigc(list_url_bigc)
  File "/opt/airflow/dags/utils/get_data_bigc.py", line 45, in get_data_bigc
    list_regex = re.compile(f'^list_brand_{category_search}', re.IGNORECASE)
NameError: name 're' is not defined
[2024-02-15T13:04:40.845+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_pipeline, task_id=get_data_from_bigc_and_makro, execution_date=20240215T130437, start_date=20240215T130439, end_date=20240215T130440
[2024-02-15T13:04:40.855+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task get_data_from_bigc_and_makro (name 're' is not defined; 1352)
[2024-02-15T13:04:40.894+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-15T13:04:40.908+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
