[2024-02-15T13:06:04.261+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:06:02.425261+00:00 [queued]>
[2024-02-15T13:06:04.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:06:02.425261+00:00 [queued]>
[2024-02-15T13:06:04.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-15T13:06:04.272+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_bigc_and_makro> on 2024-02-15 13:06:02.425261+00:00
[2024-02-15T13:06:04.277+0000] {standard_task_runner.py:57} INFO - Started process 1380 to run task
[2024-02-15T13:06:04.283+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_pipeline', 'get_data_from_bigc_and_makro', 'manual__2024-02-15T13:06:02.425261+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmpm_ha8322']
[2024-02-15T13:06:04.288+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask get_data_from_bigc_and_makro
[2024-02-15T13:06:04.344+0000] {task_command.py:415} INFO - Running <TaskInstance: my_pipeline.get_data_from_bigc_and_makro manual__2024-02-15T13:06:02.425261+00:00 [running]> on host c0165191c622
[2024-02-15T13:06:04.399+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='my_pipeline' AIRFLOW_CTX_TASK_ID='get_data_from_bigc_and_makro' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T13:06:02.425261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-15T13:06:02.425261+00:00'
[2024-02-15T13:06:23.756+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_pipeline.py", line 130, in get_data_from_bigc_and_makro
    bigc_and_makro_df = pd.concat([bigc_df, makro_df], ignore_index=False)
NameError: name 'pd' is not defined
[2024-02-15T13:06:23.772+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_pipeline, task_id=get_data_from_bigc_and_makro, execution_date=20240215T130602, start_date=20240215T130604, end_date=20240215T130623
[2024-02-15T13:06:23.781+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task get_data_from_bigc_and_makro (name 'pd' is not defined; 1380)
[2024-02-15T13:06:23.846+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-15T13:06:23.871+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
